//
//  Singletons.swift
//  GPS
//
//  Created by Marin on 04.01.2025.
//

let translate: [Language: [String: String]] = [
    .eng: [
            "login": "Log In",
            "plsauth": "Please authenticate.",
            "authing0": "Authenticating, please wait",
            "authing1": "Authenticating, please wait.",
            "authing2": "Authenticating, please wait..",
            "authing3": "Authenticating, please wait...",
            "servconat0": "Server connection attempt",
            "servconat1": "Server connection attempt.",
            "servconat2": "Server connection attempt..",
            "servconat3": "Server connection attempt...",
            "incpaslog": "Incorrect password or login!",
            "settings": "SETTINGS",
            "enterip": "Enter IP",
            "enterport": "Enter Port",
            "sellang": "Select language",
            "savelogpas": "Save login or password",
            "cancel": "Cancel",//11
            "close": "Close",
            "alert": "Alert!",
            "sure?": "Are you sure you want to save the changes?",
            "yes": "Yes",
            "no": "No",
            "sgtracker": "Search GPS Tracker",
            "sortby": "Sort by",
            "name": "Name",
            "battery": "Battery",
            "online": "Online",
            "network" : "Network 📶:",
            "gps" : "GPS 🛰️:",
            "speed" : "Speed ➡️:",
            "time_updated" : "Time 🕒:",
        ],
    .ru: [
            "login": "Войти",
            "plsauth": "Пожалуйста, авторизуйтесь.",
            "authing0": "Авторизация, подождите",
            "authing1": "Авторизация, подождите.",
            "authing2": "Авторизация, подождите..",
            "authing3": "Авторизация, подождите...",
            "servconat0": "Попытка подключения к серверу",
            "servconat1": "Попытка подключения к серверу.",
            "servconat2": "Попытка подключения к серверу..",
            "servconat3": "Попытка подключения к серверу...",
            "incpaslog": "Неверный логин или пароль!",
            "settings": "НАСТРОЙКИ",
            "enterip": "Введите IP",
            "enterport": "Введите порт",
            "sellang": "Выберите язык",
            "savelogpas": "Сохранить логин или пароль",
            "cancel": "Отмена",//
            "close": "Закрыть",
            "alert": "Внимание!",
            "sure?": "Вы уверены, что хотите сохранить изменения?",
            "yes": "Да",
            "no": "Нет",
            "sgtracker": "Поиск GPS-трекера",
            "sortby": "Сортировать по",
            "name": "Имя",
            "battery": "Батарея",
            "gps": "GPS",
            "online": "Онлайн",
            "time_updated " : "Time 🕒:",

        ],
    .ro: [
            "login": "Autentificare",
            "plsauth": "Vă rugăm să vă autentificați",
            "authing0": "Autentificare, așteptați",
            "authing1": "Autentificare, așteptați.",
            "authing2": "Autentificare, așteptați..",
            "authing3": "Autentificare, așteptați...",
            "servconat0": "Încercare de conectare la server",
            "servconat1": "Încercare de conectare la server.",
            "servconat2": "Încercare de conectare la server..",
            "servconat3": "Încercare de conectare la server...",
            "incpaslog": "Parolă sau login incorect!",
            "settings": "SETĂRI",
            "enterip": "Introduceți IP",
            "enterport": "Introduceți portul",
            "sellang": "Selectați limba",
            "savelogpas": "Salvați loginul sau parola",
            "cancel": "Anulare",//11
            "close": "Închide",
            "alert": "Alertă!",
            "sure?": "Sunteți sigur că doriți să salvați modificările?",
            "yes": "Da",
            "no": "Nu",
            "sgtracker": "Căutare GPS Tracker",
            "sortby": "Sortare după",
            "name": "Nume",
            "battery": "Baterie",
            "gps": "GPS",
            "online": "Online",
            "time_updated " : "Time 🕒:",

        ]
    ]

